### ISSUE TITLE
Kundentermin organisieren

### ISSUE THREAD

**Issue by cr4yfish** [B4-Group/swe_b4#1]

**Comment by 4mierS** [comment]
Welche Fragen sollen gestellt werden ?
Was soll aufgeschrieben werden ?
 -> Wo liegen die **Prioritäten** ?


Termin am Freitag, den 07.10 um 17 Uhr 
Eupener Str. 70, 52066 Aachen vor dem **G-Gebäude**

**Comment by cr4yfish** [comment]
> Welche Fragen sollen gestellt werden ? Was soll aufgeschrieben werden ? -> Wo liegen die **Prioritäten** ?

[Fragenkatalog ist auf Gdrive.](https://docs.google.com/document/d/1fodFRFdPA8OORASs4IQSsjZnsJVIjUDq7hwUwUTis1o/edit?usp=sharing)

> Was soll aufgeschrieben werden ?

Am besten wir schreiben so viel wie möglich mit.

>Wo liegen die Prioritäten ?

Ist auch im Fragenkatalog.
