### ISSUE TITLE
Player in Wall

### ISSUE THREAD

**Issue by 4mierS** [B4-Group/swe_b4#113]
# What is going on
If you are standing or going under the wall, half of the player head is inside the wall

# What should happen
the head need to be over the wall

# Steps to reproduce
go to a position, where the player is going under a wall which is horizontal

Pullrequest: #112
[a7502ec]

# Screenshots
![image](https://user-images.githubusercontent.com/85135956/211918776-f3a15bfa-a61b-4aee-8d29-dbcf1c4f2330.png)

**Comment by cr4yfish** [comment]
How is this still a thing? I fixed this already.
