### ISSUE TITLE
Door dont open

### ISSUE THREAD

**Issue by 4mierS** [B4-Group/swe_b4#115]
# What is going on
[Sometimes] the door stay closed although u did the puzzle
After that u cant do the quest second time, because u did the puzzle already

# What should happen
The door opens after i compleded the puzzle

# Steps to reproduce
Go to a door and compled the puzzle rightly 

# Platform
 
 - In Editor: Inside of Unity
 - Version [e.g. v1.0.0-modified] // The Game Version you used (add a "modified", if you used a modified version. You can also reference the PR with #[112])

# Additional Information
Maybe the issue happens, because i stand too close to the door

**Comment by leonlaas** [comment]
In welchem Level war das und welche Tür?

**Comment by 4mierS** [comment]
Die erste Tür. Aber das passiert sehr selten. Also oftmals öffnet die Tür. Manchmal öffnet und schließt die Tür sich wieder, bevor man als Spieler da durchlaufen kann. Und wenn man einmal das Rätsel gemacht hat, dann kann man das nicht nochmal machen. Somit heißt es, dass die Tür für immer zu bleibt @leonlaas

**Comment by leonlaas** [comment]
In welchem Level? Und teste das bitte nochmal wenn meine PR durch ist. Die fixt ein paar bugs mit Türen und Rätseln die eigentlich garnicht auftreten sollten :D

**Comment by 4mierS** [comment]
That bug happens in tutorial

**Comment by cr4yfish** [comment]
# Steps to reproduce:
1. Go into any level
2. Restart level
3. Open a puzzle
4. Finish the puzzle
5. Observe the door opening and then closing again
