### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by 4mierS** [B4-Group/swe_b4#116]
# What is going on
Music dont restart 
If the game over sound comes, the music dont start again, after restarting the game
If restarting before you die, the music dont start from the beginning 

# What should happen
Music need to start after restart from the beginning 

# Steps to reproduce
Die

# Platform
 - In Editor: Both
 - Version v1.0.0

**Comment by leonlaas** [comment]
In welchem Level war das und welche Tür?
