### ISSUE TITLE
Sound sliders UI blocking screen

### ISSUE THREAD

**Issue by leonlaas** [B4-Group/swe_b4#117]
# What is going on
Sound sliders blocking screen even when not visible

# What should happen
When the sliders are not visible they should not block any other inputs

# Steps to reproduce
1. open Simonsays puzzle
2. try to press bottom left button

**Comment by NamoPhoenix** [comment]
![image](https://user-images.githubusercontent.com/60812574/212099681-9a873101-9cf5-47f9-91b0-a9ac7613e507.png)

Auch wenn das Pausenmenu geschlossen ist, kann man das Simon Says Objekt, Unten Links nicht "anclicken"

**Comment by krumbs8749** [comment]
Das könnte hier vllt daran leider 
![image](https://user-images.githubusercontent.com/69641252/212137940-dcfef94f-4020-4e5f-8878-e1a1b86e52f4.png)

visibility muss hier durch display ersetzt werden.

**Comment by cr4yfish** [comment]
> Das könnte hier vllt daran leider ![image](https://user-images.githubusercontent.com/69641252/212137940-dcfef94f-4020-4e5f-8878-e1a1b86e52f4.png)
> 
> visibility muss hier durch display ersetzt werden.

Ja das ist die Lösung.
