### ISSUE TITLE
Pausenmenü bug -> Movement not re-enabled

### ISSUE THREAD

**Issue by cr4yfish** [B4-Group/swe_b4#16]
# What is going on?
After closing the Pausenmenü, the Player movement is not re-enabled before hitting "esc".

# What should happen?
Player Movement should be enabled automatically after closing the Pausenmenü.

# Steps to reproduce
1. Go ingame
2. Open Pausenmenü
3. Close Pausenmenü

**Comment by krumbs8749** [comment]
That's strange. How did you close the Pausenmenü? By clicking Fortsetzen?

**Comment by cr4yfish** [comment]
> That's strange. How did you close the Pausenmenü? By clicking Fortsetzen?

Yes.

**Comment by cr4yfish** [comment]
Hat sich selbst gefixed. Kann das Issue nicht mehr reproducen.

**Comment by cr4yfish** [comment]
Wird clsoed beim mergen von #19
