### ISSUE TITLE
Throwing animation not stopping sometimes

### ISSUE THREAD

**Issue by cr4yfish** [B4-Group/swe_b4#18]
# What is going on?
When spamming "left mouse click" the throwing animation does not stop afterwards. You have to "left mouse click" once again to disable the animation. So the animation acts as a switch when spamming and as a trigger when tapping.

# What should happen?
The throwing animation should only play during shooting and always act as a trigger, not as a switch.

# Steps to reproduce
1. Go ingame
2. Start spamming "left mouse click"
3. Observe the throwing animation still going
4. Stop and wait for a small amount of time (~0.5s)
5. Left click once again
6. Observe the throwing animation has stopped

**Comment by NamoPhoenix** [comment]
liegt daran das du vor 6 tagen bei Playercontroller die Methode "onfire" in einer anderen methode aufgerufen hast

**Comment by cr4yfish** [comment]
Closed also?
