### ISSUE TITLE
Timer not working

### ISSUE THREAD

**Issue by cr4yfish** [B4-Group/swe_b4#21]
# What is going on?
The Timer is not working currently.

# What should happen?
It should start counting on game start and stop counting on level done and pausenmenu active

# Steps to reproduce
1. Go ingame
2. Observe Timer not counting
![image](https://user-images.githubusercontent.com/58395553/202864575-950d1de2-83e7-4b02-81ac-18d4a2412803.png)

**Comment by cr4yfish** [comment]
Closes on #19

**Comment by krumbs8749** [comment]
> Closes in #19

Where was the Bug actually because it works on mine. Or was it because of the merge? Same with Pausenmenu
