### ISSUE TITLE
NextLevel not working

### ISSUE THREAD

**Issue by cr4yfish** [B4-Group/swe_b4#53]
# What is going on?
Clicking "next level" is not working

# What should happen?
"Next level" should initiate the next level.

# Steps to reproduce
1. Go ingame
2. Complete a level
3. Click on "next level"
4. Observe nothing happening

**Comment by krumbs8749** [comment]
**Commenting this line out in GameCompleted allow GameCompleted.cs script to run properly (which finally allows the LevelDone screen to show the correct number of stars and hearts ):**
![image](https://user-images.githubusercontent.com/69641252/207102648-bda403f8-02a0-466d-911e-9e660976913f.png)

**However i noticed the string "Lade Level: " was included as parameter in the call of LoadLevel function:**
![image](https://user-images.githubusercontent.com/69641252/207101636-b46bced1-cb6d-432d-821b-89e40341d31c.png)

**After deleting the string, this exception is however thrown lol and i dont know anymore:**
![image](https://user-images.githubusercontent.com/69641252/207102382-77dcdfe7-1e0f-434b-8d76-1881ef262a1d.png)

**Comment by cr4yfish** [comment]
No, the whole code didn't make any sense to begin with. I fixed it in #48

**Comment by krumbs8749** [comment]
nice
