### ISSUE TITLE
Tippsystem ausbleden

### ISSUE THREAD

**Issue by NamoPhoenix** [B4-Group/swe_b4#65]
# What feature is missing?
You should be able to close the "tipp" 

# Source:
Visual comfort ? it blocks the view of puzzel elements

**Comment by cr4yfish** [comment]
Isn't this already in the game? It worked during the client meeting. Did @NamoPhoenix already fix it?

**Comment by cr4yfish** [comment]
Ok habs jetzt getestet. Funktioniert nicht.
![image](https://user-images.githubusercontent.com/58395553/210781239-3cc5ab27-e422-415c-b044-b3487b6e5aa1.png)
