### ISSUE TITLE
Sound Regler fehlerhaft

### ISSUE THREAD

**Issue by NamoPhoenix** [B4-Group/swe_b4#67]
# What is going on
"Audio Regler" doesn't safe the settings after changing it and switching menu´s
"Audio Changes" doesnt work as intended
- Audio doesnt stop if I deactivate sound
- Audio Menu doesnt work in the ESC menu at all

# What should happen

# Additional Information
I think Lucas already knows about the Problems, im just putting it here to be sure

**Comment by NamoPhoenix** [comment]
funktioniert jz bei mir aufeinmal

**Comment by cr4yfish** [comment]
Ist das nochmal aufgetreten? Sonst kannst du das issue auch closen @NamoPhoenix .
