### ISSUE TITLE
Calculator Puzzle not following the rules of math

### ISSUE THREAD

**Issue by cr4yfish** [B4-Group/swe_b4#75]
# What is going on
When trying to solve a Calculator Puzzle, the math is not adding up.

# What should happen
When entering the correct numbers, the puzzle should solve.

# Steps to reproduce
1. Enter a Calculator Puzzle
2. Enter the correct numbers
3. Hit enter
4. Observe the puzzle not solving

# Platform
 - In Editor: [e.g. No] // Whether you played the Game inside of Unity or used a Build
 - Version [e.g. v0.8.1-modified] // The Game Version you used (add a "modified", if you used a modified version. You can also reference the PR with #[pr-number])

# Screenshots

# Additional Information

**Comment by leonlaas** [comment]
I think the calculator puzzle is meant, right?

**Comment by leonlaas** [comment]
If calculator was meant its fixed in Pr#86  https://github.com/B4-Group/swe_b4/pull/86

**Comment by cr4yfish** [comment]
Fixed
