### ISSUE TITLE
Traps not playing Animations

### ISSUE THREAD

**Issue by 4mierS** [B4-Group/swe_b4#82]
# What is going on
Traps (Spike) spielen nicht die Animation

# What should happen
Animation muss abgespielt werden, nachdem der Spieler damage von den Traps bekommt

# Steps to reproduce

1. Go to Traps (In der Mitte der 1.Map)
2. Lauf gegen die Trap -> Der Spieler bekommt Damage

# Platform
 - In Editor: Im Builder 

# Additional Information
Problem kann vlt gelöst werden, wenn im Trap-Script manuell der Parameter für die Animation gesetzt wird

**Comment by cr4yfish** [comment]
Note that this is in @4mierS 's fork only right now.

**Comment by 4mierS** [comment]
that bug make no sense

**Comment by 4mierS** [comment]
# Close bug
## Reason
I think, i can close the bug issue, because the bug cant be fixed by us.

## Improved
Now, the animation plays, except the player stop running just before the animation plays
