### ISSUE TITLE
Zombies being added by restarting level

### ISSUE THREAD

**Issue by 4mierS** [B4-Group/swe_b4#83]
# What is going on
Wenn im GameOverMenü das Spiel resartet wird, wird ein Enemy hinzugefügt, obwohl es bereits einen gibt
-> After Restart, Quantity of Enemys = n + 1

# What should happen
Es soll nur einen Enemy auf der Map geben

# Steps to reproduce
1. 3x Selfdamage
2. Restart im GameOverMenü anklicken 
3. Zu den Enemys gehen 

# Platform
 - In Editor: Builder
# Screenshots
![image](https://user-images.githubusercontent.com/85135956/209967759-4e26e572-fa48-4fcf-889d-d5af8e7a168d.png)

**Comment by cr4yfish** [comment]
Fix sollte easy sein.
Im der restart Methode, da wo der Enemy gespawnt wird muss man lediglich alles in in ein if packen.
`if(!FindGameObjectByTagName("Enemy")) {
   ...
}
`

**Comment by 4mierS** [comment]
> Fix sollte easy sein. Im der restart Methode, da wo der Enemy gespawnt wird muss man lediglich alles in in ein if packen. `if(!FindGameObjectByTagName("Enemy")) { ... } `
> 
> Ich kann das morgen machen.

Ich wollte nichts in den anderen Scripts ändern

**Comment by cr4yfish** [comment]
Wow, der Fix war noch einfacher als ich dachte haha.
![image](https://user-images.githubusercontent.com/58395553/210665387-d62a319b-0080-4846-aee3-a5af0d8a9b06.png)
