### ISSUE TITLE
Game Over Stars

### ISSUE THREAD

**Issue by 4mierS** [B4-Group/swe_b4#92]
# What is going on
Nach jedem Restart werden die Stars im Game Over Menü um 3 erhöht

# What should happen
Nach jeden Restart wird der Sterncounter auf 0 gesetzt und im Game Over Menü werden nur 3 Sterne angezeigt

# Steps to reproduce
1. Stirb 
2. Restarte das Game

# Platform
 - In Editor: Unity
 - Version: PR#87

# Screenshots
![image](https://user-images.githubusercontent.com/85135956/210748206-4877f5f3-7f84-49e7-a1b6-120c97512b5c.png)

**Comment by krumbs8749** [comment]
Das liegt daran, dass die alte Stats nicht gelöscht wurden. Dieses Bug sollte mit diesem Code lösbar sein (auch für timeContainer) 

![image](https://user-images.githubusercontent.com/69641252/210749627-939c7cfd-9ee6-4c17-a09c-64f623e6c494.jpeg)
